[package]
name = "voice"
version.workspace = true
publish = false
authors.workspace = true
edition.workspace = true

[dependencies]
bincode = { version = "2.0.1", features = ["derive"] }
strum = { version = "0.27.2", features = ["derive"] }
